'\" t
.\"     Title: lod_model
.\"    Author: Mo McRoberts
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 07/07/2015
.\"    Manual: Library functions
.\"    Source: Linked Open Data client
.\"  Language: English
.\"
.TH "LOD_MODEL" "3" "07/07/2015" "Linked Open Data client" "Library functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lod_model \- Obtain a librdf model associated with a context
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <liblod\&.h>
.fi
.ft
.HP \w'librdf_model\ *lod_model('u
.BI "librdf_model *lod_model(LODCONTEXT\ *" "context" ");"
.SH "DESCRIPTION"
.PP

\fBlod_model\fR
obtains the
\fBlibrdf_model\fR
which is associated with
\fIcontext\fR\&.
.SH "RETURN VALUE"
.PP
Upon success,
\fBlod_model\fR
returns the
\fBlibrdf_model\fR
object associated with
\fIcontext\fR\&.
.PP
If an error occurs,
\fBlod_model\fR
returns
\fBNULL\fR\&.
\fBlod_errmsg\fR
can be used to obtain a description of the error condition\&.
.SH "SEE ALSO"
.PP

\m[blue]\fB\fBliblod\fR(3)\fR\m[],
\m[blue]\fB\fBlod_set_model\fR(3)\fR\m[],
\m[blue]\fB\fBlod_storage\fR(3)\fR\m[],
\m[blue]\fB\fBlod_world\fR(3)\fR\m[],
\m[blue]\fB\fBlod_curl\fR(3)\fR\m[],
\m[blue]\fB\fBlod_errmsg\fR(3)\fR\m[],
