'\" t
.\"     Title: lod_instance_exists
.\"    Author: Mo McRoberts
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 04/30/2014
.\"    Manual: Library functions
.\"    Source: Linked Open Data client
.\"  Language: English
.\"
.TH "LOD_INSTANCE_EXISTS" "3" "04/30/2014" "Linked Open Data client" "Library functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lod_instance_exists \- Check that the subject referred to by a liblod instance exists
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <liblod\&.h>
.fi
.ft
.HP \w'int\ lod_instance_exists('u
.BI "int lod_instance_exists(LODINSTANCE\ *" "instance" ");"
.SH "DESCRIPTION"
.PP

\fBlod_instance_exists\fR
checks that the subject of an instance exists in the associated context\*(Aqs model\&.
.PP
A
liblod
instance is a simple kind of query for any triples whose subject matches the URI provided to
\fBlod_resolve\fR\&. There are various circumstances by which
\fBlod_resolve\fR
can successfully return an instance, but that the subject of the instance doesn\*(Aqt actually exist in the data held by the model\&.
.PP
Because an instance is a query against a model, a call to
\fBlod_instance_exists\fR
may have different results at different times\&. For example, it might initially return zero (false), but following a new call to
\fBlod_resolve\fR
(or manually adding triples to the associated
librdf
model), the next call might return non\-zero (true)\&.
.SH "RETURN VALUE"
.PP
If the subject of the instance does not exist in the context,
\fBlod_instance_exists\fR
returns zero\&.
.PP
Otherwise,
\fBlod_instance_exists\fR
returns a positive integer\&.
.SH "SEE ALSO"
\m[blue]\fB\fBlod_resolve\fR(3)\fR\m[]\&.
  