'\" t
.\"     Title: lod_instance_primarytopic
.\"    Author: Mo McRoberts
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 05/05/2014
.\"    Manual: Library functions
.\"    Source: Linked Open Data client
.\"  Language: English
.\"
.TH "LOD_INSTANCE_PRIMARY" "3" "05/05/2014" "Linked Open Data client" "Library functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lod_instance_primarytopic \- Follow a foaf:primaryTopic reference
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <liblod\&.h>
.fi
.ft
.HP \w'LODINSTANCE\ *lod_instance_primarytopic('u
.BI "LODINSTANCE *lod_instance_primarytopic(LODINSTANCE\ *" "instance" ");"
.SH "DESCRIPTION"
.PP
The
\fBlod_instance_primarytopic\fR
attempts to follow a
foaf:primaryTopic
relationship between the subject of the supplied instance and another resource\&.
.PP
If such a triple exists in the associated context\*(Aqs model, a new instance will be created with the object of the triple as its subject\&.
.PP
Note that the object of the
foaf:primaryTopic
triple may not itself be present in the model, and you should use
\fBlod_instance_exists\fR
on the newly\-returned instance to check\&.
.SH "RETURN VALUE"
.PP
If a
foaf:primaryTopic
triple exists where the subject matches that of the instance,
\fBlod_instance_primarytopic\fR
returns a new instance whose subject is the object of that triple\&.
.PP
If no such triple was found, or an error occurs,
\fBNULL\fR
will be returned instead\&. Use
\fBlod_error\fR
to determine whether an error occurred, or whether an appropriate triple was simply absent\&.
.SH "SEE ALSO"
\m[blue]\fB\fBliblod\fR(3)\fR\m[],
	\m[blue]\fB\fBlod_resolve\fR(3)\fR\m[],
	\m[blue]\fB\fBlod_error\fR(3)\fR\m[],
	\m[blue]\fB\fBlod_instance_destroy\fR(3)\fR\m[]\&.
  