'\" t
.\"     Title: lod_instance_stream
.\"    Author: Mo McRoberts
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 07/07/2015
.\"    Manual: Library functions
.\"    Source: Linked Open Data client
.\"  Language: English
.\"
.TH "LOD_INSTANCE_STREAM" "3" "07/07/2015" "Linked Open Data client" "Library functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lod_instance_stream \- Return a librdf_stream for an instance
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <liblod\&.h>
.fi
.ft
.HP \w'librdf_stream\ *lod_instance_stream('u
.BI "librdf_stream *lod_instance_stream(LODINSTANCE\ *" "instance" ");"
.SH "DESCRIPTION"
.PP

\fBlod_instance_stream\fR
returns a
librdf
stream containing all of the triples in the associated context\*(Aqs model where the subject of the triple is the subject of the instance\&.
.PP
A call to
\fBlod_instance_stream\fR
is the equivalent of calling
\fBlibrdf_model_find_statements\fR
on the context\*(Aqs model, passing a partial
librdf
statement where the subject matches that of the instance\&.
.PP
The resulting stream should be freed with a call to
\fBlibrdf_free_stream\fR
once it is no longer required\&.
.SH "RETURN VALUE"
.PP
Upon success,
\fBlod_instance_stream\fR
returns a new
librdf
stream\&.
.PP
If an error occurs,
\fBlod_instance_stream\fR
returns
\fBNULL\fR\&. A description of the error condition can be obtained using
\fBlod_errmsg\fR\&.
.SH "SEE ALSO"
\m[blue]\fB\fBliblod\fR(3)\fR\m[],
	\m[blue]\fB\fBlod_resolve\fR(3)\fR\m[],
	\m[blue]\fB\fBlod_errmsg\fR(3)\fR\m[],
	\m[blue]\fB\fBlod_instance_exists\fR(3)\fR\m[],
	\m[blue]\fB\fBlibrdf_free_stream\fR(3)\fR\m[],
	\m[blue]\fB\fBlibrdf_model_find_statements\fR(3)\fR\m[]\&.
  